ingredients = {
    { name = "butterflywings", name_cn = "蝴蝶翅膀", health = 8, hunger = 9.4, sanity = 0, decoration = 2, type = VEGGIE }, 
    { name = "red_cap_cooked", name_cn = "熟红蘑菇", health = 1, hunger = 0, sanity = -10, veggie = 0.5, precook = 1, type = VEGGIE }, 
    { name = "batwing", name_cn = "洞穴蝙蝠翅膀", health = 3, hunger = 12.5, sanity = -10, meat = 0.5, type = MEAT }, 
    { name = "oceanfish_medium_8_inv", name_cn = "冰鲷鱼", health = 8, hunger = 25, sanity = 0, fish = 1, meat = 1, frozen = 1, type = MEAT }, 
    { name = "froglegs_cooked", name_cn = "熟蛙腿", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, precook = 1, type = MEAT }, 
    { name = "eggplant", name_cn = "茄子", health = 8, hunger = 25, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "moon_cap_cooked", name_cn = "熟月亮蘑菇", health = 0, hunger = -12.5, sanity = -10, veggie = 0.5, precook = 1, type = VEGGIE }, 
    { name = "dragonfruit_cooked", name_cn = "熟火龙果", health = 20, hunger = 12.5, sanity = 0, fruit = 1, precook = 1, type = VEGGIE }, 
    { name = "batnose", name_cn = "裸露鼻孔", health = 3, hunger = 12.5, sanity = -10, meat = 0.5, type = MEAT }, 
    { name = "eel_cooked", name_cn = "熟鳗鱼", health = 8, hunger = 12.5, sanity = 0, fish = 1, meat = 0.5, precook = 1, type = MEAT }, 
    { name = "blue_cap", name_cn = "采摘的蓝蘑菇", health = 20, hunger = 12.5, sanity = -15, veggie = 0.5, type = VEGGIE }, 
    { name = "oceanfish_medium_3_inv", name_cn = "浮夸狮子鱼", health = 8, hunger = 25, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "tallbirdegg", name_cn = "高脚鸟蛋", health = 3, hunger = 25, sanity = 0, egg = 4, type = MEAT }, 
    { name = "batnose_cooked", name_cn = "炭烤鼻孔", health = 8, hunger = 18.8, sanity = 0, meat = 0.5, precook = 1, type = MEAT }, 
    { name = "berries_juicy_cooked", name_cn = "烤多汁浆果", health = 3, hunger = 18.8, sanity = 0, fruit = 0.5, precook = 1, type = VEGGIE }, 
    { name = "oceanfish_medium_4_inv", name_cn = "黑鲶鱼", health = 8, hunger = 25, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "pepper_cooked", name_cn = "烤辣椒", health = -3, hunger = 9.4, sanity = -10, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "oceanfish_small_1_inv", name_cn = "小孔雀鱼", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "barnacle", name_cn = "藤壶", health = 0, hunger = 12.5, sanity = -5, meat = 0.25, fish = 0.25, type = MEAT }, 
    { name = "acorn_cooked", name_cn = "烤桦栗果", health = 1, hunger = 9.4, sanity = 0, seed = 1, type = SEEDS }, 
    { name = "oceanfish_medium_5_inv", name_cn = "玉米鳕鱼", health = 3, hunger = 25, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "tomato", name_cn = "番茄", health = 3, hunger = 12.5, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "asparagus_cooked", name_cn = "烤芦笋", health = 3, hunger = 25, sanity = 0, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "moon_cap", name_cn = "月亮蘑菇", health = 0, hunger = 12.5, sanity = 10, veggie = 0.5, type = VEGGIE }, 
    { name = "oceanfish_medium_6_inv", name_cn = "花锦鲤", health = 8, hunger = 25, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "trunk_cooked", name_cn = "象鼻排", health = 40, hunger = 75, sanity = 0, meat = 1, type = MEAT }, 
    { name = "forgetmelots", name_cn = "必忘我", health = 0, hunger = 0, sanity = 1, decoration = 1, type = VEGGIE }, 
    { name = "red_cap", name_cn = "采摘的红蘑菇", health = -20, hunger = 12.5, sanity = 0, veggie = 0.5, type = VEGGIE }, 
    { name = "onion_cooked", name_cn = "烤洋葱", health = 1, hunger = 9.4, sanity = -5, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "bird_egg", name_cn = "鸟蛋", health = 0, hunger = 9.4, sanity = 0, egg = 1, type = MEAT }, 
    { name = "froglegs", name_cn = "蛙腿", health = 0, hunger = 12.5, sanity = -10, meat = 0.5, type = MEAT }, 
    { name = "drumstick_cooked", name_cn = "炸鸟腿", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, precook = 1, type = MEAT }, 
    { name = "fig", name_cn = "无花果", health = 0, hunger = 12.5, sanity = 0, fruit = 0.5, type = VEGGIE }, 
    { name = "eel", name_cn = "鳗鱼", health = 3, hunger = 9.4, sanity = 0, meat = 0.5, fish = 1, type = MEAT }, 
    { name = "carrot_cooked", name_cn = "烤胡萝卜", health = 3, hunger = 12.5, sanity = 0, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "smallmeat", name_cn = "小肉", health = 0, hunger = 12.5, sanity = -10, meat = 0.5, type = MEAT }, 
    { name = "durian_cooked", name_cn = "超臭榴莲", health = 0, hunger = 25, sanity = -5, monster = 1, fruit = 1, precook = 1, type = VEGGIE }, 
    { name = "pondfish", name_cn = "淡水鱼", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "oceanfish_small_9_inv", name_cn = "口水鱼", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "oceanfish_medium_7_inv", name_cn = "金锦鲤", health = 8, hunger = 25, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "milkywhites", name_cn = "乳白物", health = 8, hunger = 12.5, sanity = -20, dairy = 1, type = GENERIC }, 
    { name = "monstermeat_dried", name_cn = "怪物肉干", health = -3, hunger = 18.8, sanity = -5, dried = 1, meat = 1, monster = 1, type = MEAT }, 
    { name = "refined_dust", name_cn = "尘土块", health = 10, hunger = 1, sanity = 0, decoration = 2, type = ELEMENTAL }, 
    { name = "pomegranate", name_cn = "石榴", health = 3, hunger = 9.4, sanity = 0, fruit = 1, type = VEGGIE }, 
    { name = "tomato_cooked", name_cn = "烤番茄", health = 20, hunger = 12.5, sanity = 0, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "moonbutterflywings", name_cn = "月蛾翅膀", health = 8, hunger = 9.4, sanity = 15, decoration = 2, type = VEGGIE }, 
    { name = "fishmeat_small_cooked", name_cn = "熟小鱼块", health = 1, hunger = 12.5, sanity = 0, fish = 0.5, meat = 0.5, precook = 1, type = MEAT }, 
    { name = "rock_avocado_fruit_ripe", name_cn = "成熟石果", health = 1, hunger = 12.5, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "wormlight", name_cn = "发光浆果", health = 11, hunger = 25, sanity = -10, fruit = 1, type = VEGGIE }, 
    { name = "fishmeat_cooked", name_cn = "鱼排", health = 8, hunger = 25, sanity = 0, fish = 1, meat = 1, precook = 1, type = MEAT }, 
    { name = "garlic", name_cn = "大蒜", health = 0, hunger = 9.4, sanity = -10, veggie = 1, type = VEGGIE }, 
    { name = "dragonfruit", name_cn = "火龙果", health = 3, hunger = 9.4, sanity = 0, fruit = 1, type = VEGGIE }, 
    { name = "fish", name_cn = "鱼", health = 1, hunger = 12.5, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "pepper", name_cn = "辣椒", health = -20, hunger = 9.4, sanity = -15, veggie = 1, type = VEGGIE }, 
    { name = "wormlight_lesser", name_cn = "小发光浆果", health = 3, hunger = 12.5, sanity = -10, fruit = 0.5, type = VEGGIE }, 
    { name = "durian", name_cn = "榴莲", health = -3, hunger = 25, sanity = -5, monster = 1, fruit = 1, type = VEGGIE }, 
    { name = "onion", name_cn = "洋葱", health = 0, hunger = 9.4, sanity = -10, veggie = 1, type = VEGGIE }, 
    { name = "barnacle_cooked", name_cn = "熟藤壶", health = 1, hunger = 12.5, sanity = 0, meat = 0.25, fish = 0.25, type = MEAT }, 
    { name = "royal_jelly", name_cn = "蜂王浆", health = 40, hunger = 12.5, sanity = 15, sweetener = 3, type = GENERIC }, 
    { name = "garlic_cooked", name_cn = "烤大蒜", health = 1, hunger = 9.4, sanity = -5, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "oceanfish_small_5_inv", name_cn = "爆米花鱼", health = 3, hunger = 12.5, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "oceanfish_small_8_inv", name_cn = "炽热太阳鱼", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "ice", name_cn = "冰", health = 0.5, hunger = 2.3, sanity = 0, frozen = 1, type = GENERIC }, 
    { name = "oceanfish_small_7_inv", name_cn = "花朵金枪鱼", health = 0, hunger = 12.5, sanity = -10, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "eggplant_cooked", name_cn = "烤茄子", health = 20, hunger = 25, sanity = 0, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "berries", name_cn = "浆果", health = 0, hunger = 9.4, sanity = 0, fruit = 0.5, type = VEGGIE }, 
    { name = "honey", name_cn = "蜂蜜", health = 3, hunger = 9.4, sanity = 0, sweetener = 1, type = GENERIC }, 
    { name = "asparagus", name_cn = "芦笋", health = 3, hunger = 12.5, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "cactus_flower", name_cn = "仙人掌花", health = 8, hunger = 12.5, sanity = 5, veggie = 0.5, type = VEGGIE }, 
    { name = "fishmeat_small", name_cn = "小鱼块", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "cave_banana", name_cn = "香蕉", health = 1, hunger = 12.5, sanity = 0, fruit = 1, type = VEGGIE }, 
    { name = "batwing_cooked", name_cn = "熟蝙蝠翅膀", health = 8, hunger = 18.8, sanity = 0, meat = 0.5, precook = 1, type = MEAT }, 
    { name = "trunk_winter", name_cn = "冬象鼻", health = 30, hunger = 37.5, sanity = 0, meat = 1, type = MEAT }, 
    { name = "pumpkin_cooked", name_cn = "烤南瓜", health = 8, hunger = 37.5, sanity = 0, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "trunk_summer", name_cn = "象鼻", health = 30, hunger = 37.5, sanity = 0, meat = 1, type = MEAT }, 
    { name = "plantmeat_cooked", name_cn = "熟叶肉", health = 1, hunger = 18.8, sanity = 0, meat = 1, type = MEAT }, 
    { name = "watermelon", name_cn = "西瓜", health = 3, hunger = 12.5, sanity = 5, fruit = 1, type = VEGGIE }, 
    { name = "berries_cooked", name_cn = "烤浆果", health = 1, hunger = 12.5, sanity = 0, fruit = 0.5, precook = 1, type = VEGGIE }, 
    { name = "meat_dried", name_cn = "肉干", health = 20, hunger = 25, sanity = 15, dried = 1, meat = 1, type = MEAT }, 
    { name = "corn", name_cn = "玉米", health = 3, hunger = 25, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "twigs", name_cn = "树枝", health = 0.5, hunger = 9.4, sanity = 0, inedible = 1, type = ROUGHAGE }, 
    { name = "green_cap_cooked", name_cn = "熟绿蘑菇", health = -1, hunger = 0, sanity = 15, veggie = 0.5, precook = 1, type = VEGGIE }, 
    { name = "oceanfish_small_4_inv", name_cn = "三文鱼苗", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "oceanfish_medium_1_inv", name_cn = "泥鱼", health = 8, hunger = 25, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "pondeel", name_cn = "活鳗鱼", health = 3, hunger = 9.4, sanity = 0, meat = 0.5, fish = 1, type = MEAT }, 
    { name = "goatmilk", name_cn = "带电的羊奶", health = 3, hunger = 12.5, sanity = 10, dairy = 1, type = GENERIC }, 
    { name = "carrot", name_cn = "胡萝卜", health = 1, hunger = 12.5, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "potato_cooked", name_cn = "烤土豆", health = 20, hunger = 25, sanity = 0, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "green_cap", name_cn = "采摘的绿蘑菇", health = 0, hunger = 12.5, sanity = -50, veggie = 0.5, type = VEGGIE }, 
    { name = "pumpkin", name_cn = "南瓜", health = 3, hunger = 37.5, sanity = 0, veggie = 1, type = VEGGIE }, 
    { name = "acorn", name_cn = "桦栗果", health = 1, hunger = 9.4, sanity = 0, seed = 1, type = RAW }, 
    { name = "blue_cap_cooked", name_cn = "熟蓝蘑菇", health = -3, hunger = 0, sanity = 10, veggie = 0.5, precook = 1, type = VEGGIE }, 
    { name = "fish_cooked", name_cn = "熟鱼", health = 1, hunger = 12.5, sanity = 0, fish = 1, meat = 1, precook = 1, type = MEAT }, 
    { name = "oceanfish_small_6_inv", name_cn = "落叶比目鱼", health = 0, hunger = 12.5, sanity = -10, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "meat", name_cn = "肉", health = 1, hunger = 25, sanity = -10, meat = 1, type = MEAT }, 
    { name = "watermelon_cooked", name_cn = "烤西瓜", health = 1, hunger = 12.5, sanity = 7.5, fruit = 1, precook = 1, type = VEGGIE }, 
    { name = "plantmeat", name_cn = "叶肉", health = 0, hunger = 12.5, sanity = -10, meat = 1, type = MEAT }, 
    { name = "rock_avocado_fruit_ripe_cooked", name_cn = "熟石果", health = 3, hunger = 12.5, sanity = 0, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "fishmeat", name_cn = "生鱼肉", health = 8, hunger = 25, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "cutlichen", name_cn = "苔藓", health = 3, hunger = 12.5, sanity = -5, veggie = 1, type = VEGGIE }, 
    { name = "berries_juicy", name_cn = "多汁浆果", health = 1, hunger = 12.5, sanity = 0, fruit = 0.5, type = VEGGIE }, 
    { name = "oceanfish_medium_2_inv", name_cn = "斑鱼", health = 8, hunger = 25, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "cactus_meat", name_cn = "仙人掌肉", health = -3, hunger = 12.5, sanity = -5, veggie = 1, type = VEGGIE }, 
    { name = "oceanfish_small_2_inv", name_cn = "针鼻喷墨鱼", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "bird_egg_cooked", name_cn = "熟鸟蛋", health = 0, hunger = 12.5, sanity = 0, egg = 1, precook = 1, type = MEAT }, 
    { name = "kelp", name_cn = "海带叶", health = -1, hunger = 9.4, sanity = -10, veggie = 0.5, type = VEGGIE }, 
    { name = "tallbirdegg_cooked", name_cn = "煎高脚鸟蛋", health = 0, hunger = 37.5, sanity = 0, egg = 4, precook = 1, type = MEAT }, 
    { name = "oceanfish_medium_9_inv", name_cn = "甜味鱼", health = 8, hunger = 25, sanity = 0, meat = 1, fish = 1, type = MEAT }, 
    { name = "mandrake", name_cn = "曼德拉草", health = 60, hunger = 75, sanity = 0, magic = 1, veggie = 1, type = VEGGIE }, 
    { name = "kelp_cooked", name_cn = "熟海带叶", health = 0, hunger = 9.4, sanity = -5, veggie = 0.5, precook = 1, type = VEGGIE }, 
    { name = "drumstick", name_cn = "鸟腿", health = 0, hunger = 12.5, sanity = -10, meat = 0.5, type = MEAT }, 
    { name = "monstermeat", name_cn = "怪物肉", health = -20, hunger = 18.8, sanity = -15, meat = 1, monster = 1, type = MEAT }, 
    { name = "cactus_meat_cooked", name_cn = "熟仙人掌肉", health = 1, hunger = 12.5, sanity = 15, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "butter", name_cn = "黄油", health = 40, hunger = 25, sanity = 0, dairy = 1, fat = 1, type = GENERIC }, 
    { name = "pomegranate_cooked", name_cn = "切片熟石榴", health = 20, hunger = 12.5, sanity = 0, fruit = 1, precook = 1, type = VEGGIE }, 
    { name = "fig_cooked", name_cn = "熟无花果", health = 1, hunger = 18.8, sanity = 0, fruit = 0.5, precook = 1, type = VEGGIE }, 
    { name = "cave_banana_cooked", name_cn = "熟香蕉", health = 3, hunger = 12.5, sanity = 0, fruit = 1, precook = 1, type = VEGGIE }, 
    { name = "oceanfish_small_3_inv", name_cn = "小饵鱼", health = 1, hunger = 12.5, sanity = 0, meat = 0.5, fish = 0.5, type = MEAT }, 
    { name = "corn_cooked", name_cn = "爆米花", health = 3, hunger = 12.5, sanity = 0, veggie = 1, precook = 1, type = VEGGIE }, 
    { name = "smallmeat_dried", name_cn = "小风干肉", health = 8, hunger = 12.5, sanity = 10, dried = 1, meat = 0.5, type = MEAT }, 
    { name = "potato", name_cn = "土豆", health = -3, hunger = 12.5, sanity = -5, veggie = 1, type = VEGGIE }, 
    { name = "kelp_dried", name_cn = "干海带叶", health = 1, hunger = 9.4, sanity = 10, dried = 1, veggie = 0.5, type = VEGGIE }, 
}
recipes = {
    {name = "surfnturf", name_cn = "海鲜牛排", health = 60, hunger = 37.5, sanity = 33, type = MEAT, perishtime = 4800, cooktime = 1, ingredients = {meat = {value=2.5,sign=">="}, fish =  {value=1.5,sign=">="}}, prohibit = {"frozen"} }, 
    {name = "leafymeatsouffle", name_cn = "果冻沙拉", health = 0, hunger = 37.5, sanity = 50, type = MEAT, perishtime = 2880, cooktime = 2, ingredients = {plantmeat = {value=2,sign=">="}, sweetener =  {value=2,sign=">="}}, prohibit = {} }, 
    {name = "barnaclesushi", name_cn = "藤壶握寿司", health = 40, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {barnacle = {value=1,sign=">="}, kelp =  {value=1,sign=">="}, egg =  {value=1,sign=">="}}, prohibit = {} }, 
    {name = "talleggs", name_cn = "苏格兰高鸟蛋", health = 60, hunger = 150, sanity = 5, type = MEAT, perishtime = 7200, cooktime = 2, ingredients = {tallbirdegg = {value=1,sign=">="}, veggie =  {value=1,sign=">="}}, prohibit = {} }, 
    {name = "monsterlasagna", name_cn = "怪物千层饼", health = -20, hunger = 37.5, sanity = -20, type = MEAT, perishtime = 2880, cooktime = 0.5, ingredients = {monster = {value=2,sign=">="}}, prohibit = {"inedible"} }, 
    {name = "moqueca", name_cn = "海鲜杂烩", health = 60, hunger = 112.5, sanity = 33, type = MEAT, perishtime = 3840, cooktime = 2, ingredients = {fish = {value=0.5,sign=">="}, onion = {value=1,sign=">="}, tomato = {value=1,sign=">="}}, prohibit = {"inedible"} }, 
    {name = "meatysalad", name_cn = "牛肉绿叶菜", health = 40, hunger = 75, sanity = 5, type = MEAT, perishtime = 2880, cooktime = 2, ingredients = {plantmeat = {value=1,sign=">="}, veggie =  {value=3,sign=">="}}, prohibit = {} }, 
    {name = "asparagussoup", name_cn = "芦笋汤", health = 20, hunger = 18.75, sanity = 5, type = VEGGIE, perishtime = 7200, cooktime = 0.5, ingredients = {asparagus = {value=1,sign=">="}, veggie =  {value=2,sign=">="}}, prohibit = {"inedible","meat"} }, 
    {name = "shroomcake", name_cn = "蘑菇蛋糕", health = 0, hunger = 25, sanity = 10, type = GOODIES, perishtime = 7200, cooktime = 1, ingredients = {moon_cap={value=1,sign="="}, red_cap={value=1,sign="="}, blue_cap={value=1,sign="="}, green_cap={value=1,sign="="}}, prohibit = {} }, 
    {name = "turkeydinner", name_cn = "火鸡正餐", health = 20, hunger = 75, sanity = 5, type = MEAT, perishtime = 2880, cooktime = 3, ingredients = {{drumstick={value=1,sign=">"}, meat={value=1,sign=">"}, veggie={value=0.5,sign=">="}},{drumstick={value=1,sign=">"}, meat={value=1,sign=">"}, fruit={value=0.5,sign=">="}}},prohibit = {} }, 
    {name = "fishsticks", name_cn = "炸鱼排", health = 40, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 2, ingredients = {fish={value=0.5,sign=">="}, twigs={value=1,sign="="},inedible={value=1,sign="<="}}, prohibit = {} }, 
    {name = "mandrakesoup", name_cn = "曼德拉草汤", health = 100, hunger = 150, sanity = 5, type = VEGGIE, perishtime = 2880, cooktime = 3, ingredients = {mandrake={value=1,sign=">="}}, prohibit = {} }, 
    {name = "dustmeringue", name_cn = "琥珀美食", health = 0, hunger = 12.5, sanity = 0, type = ELEMENTAL, perishtime = nil, cooktime = 2, ingredients = {refined_dust={value=1,sign=">="}}, prohibit = {} }, 
    {name = "dragonpie", name_cn = "火龙果派", health = 40, hunger = 75, sanity = 5, type = VEGGIE, perishtime = 7200, cooktime = 2, ingredients = {dragonfruit={value=1,sign=">="}}, prohibit = {"meat"} }, 
    {name = "figatoni", name_cn = "无花果意面", health = 30, hunger = 56.25, sanity = 15, type = VEGGIE, perishtime = 2880, cooktime = 2, ingredients = {fig={value=1,sign=">="}, veggie={value=2,sign=">="}}, prohibit = {"meat"} }, 
    {name = "ratatouille", name_cn = "蔬菜杂烩", health = 3, hunger = 25, sanity = 5, type = VEGGIE, perishtime = 7200, cooktime = 1, ingredients = {meat = {value=0.5,sign=">="}, veggie={value=0.5,sign=">="}}, prohibit = {"inedible"} }, 
    {name = "fruitmedley", name_cn = "水果圣代", health = 20, hunger = 25, sanity = 5, type = VEGGIE, perishtime = 2880, cooktime = 0.5, ingredients = {fruit = {value=3,sign=">="}}, prohibit = {"meat","veggie"}  }, 
    {name = "powcake", name_cn = "芝士蛋糕", health = -3, hunger = 0, sanity = 0, type = VEGGIE, perishtime = 9000000, cooktime = 0.5, ingredients = {{twigs = {value=1,sign=">="}, honey = {value=1,sign=">="}, corn = {value=1,sign=">="}},{twigs = {value=1,sign=">="}, honey = {value=1,sign=">="}, oceanfish_small_5_inv = {value=1,sign=">="}},{twigs = {value=1,sign=">="}, honey = {value=1,sign=">="}, oceanfish_medium_5_inv = {value=1,sign=">="}}}, prohibit = {} }, 
    {name = "justeggs", name_cn = "普通煎蛋", health = 3, hunger = 50, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {egg = {value=3,sign=">="}}, prohibit = {} }, 
    {name = "shroombait", name_cn = "酿夜帽", health = -20, hunger = 18.75, sanity = -15, type = MEAT, perishtime = 7200, cooktime = 1, ingredients = {moon_cap = {value=2,sign=">="}, monstermeat = {value=1,sign=">="}}, prohibit = {} }, 
    {name = "leafloaf", name_cn = "叶肉糕", health = 8, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 9600, cooktime = 2, ingredients = {plantmeat = {value=2,sign=">="}}, prohibit = {} }, 
    {name = "bonestew", name_cn = "炖肉汤", health = 12, hunger = 150, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 0.75, ingredients = {meat = {value=3,sign=">="}}, prohibit = {"inedible"} }, 
    {name = "meatballs", name_cn = "肉丸", health = 3, hunger = 62.5, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 0.75, ingredients = {meat = {value=1,sign=">="}}, prohibit = {"inedible"} }, 
    {name = "jellybean", name_cn = "彩虹糖豆", health = 2, hunger = 0, sanity = 5, type = GOODIES, perishtime = nil, cooktime = 2.5, ingredients = {royal_jelly = {value=1,sign=">="}}, prohibit = {"inedible","monster"} }, 
    {name = "taffy", name_cn = "太妃糖", health = -3, hunger = 25, sanity = 15, type = GOODIES, perishtime = 7200, cooktime = 2, ingredients = {sweetener = {value=3,sign=">="}}, prohibit = {"meat"} }, 
    {name = "lobsterdinner", name_cn = "龙虾正餐", health = 60, hunger = 37.5, sanity = 50, type = MEAT, perishtime = 7200, cooktime = 1, ingredients = {wobster_sheller_land = {value=1,sign=">="}, butter = {value=1,sign=">="}, meat = {value=1,sign=">="}, fish = {value=1,sign=">="}}, prohibit = {"frozen"} }, 
    {name = "gazpacho", name_cn = "芦笋冷汤", health = 3, hunger = 25, sanity = 10, type = VEGGIE, perishtime = 7200, cooktime = 0.5, ingredients = {{asparagus = {value=2,sign=">="}},{asparagus = {value=1,sign=">="},frozen = {value=2,sign=">="}}}, prohibit = {} }, 
    {name = "butterflymuffin", name_cn = "蝴蝶松饼", health = 20, hunger = 37.5, sanity = 5, type = VEGGIE, perishtime = 7200, cooktime = 2, ingredients = {{butterflywings = {value=1,sign=">="},veggie = {value=0.5,sign=">="}},{moonbutterflywings = {value=1,sign=">="},veggie = {value=0.5,sign=">="}}}, prohibit = {"meat"} }, 
    {name = "salsa", name_cn = "生鲜萨尔萨酱", health = 3, hunger = 25, sanity = 33, type = VEGGIE, perishtime = 7200, cooktime = 0.5, ingredients = {tomato = {value=1,sign=">="}, onion = {value=1,sign=">="}}, prohibit = {"inedible","meat","egg"} }, 
    {name = "kabobs", name_cn = "肉串", health = 3, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 7200, cooktime = 2, ingredients = {meat = {value=0.5,sign=">="}, twigs = {value=1,sign=">="},inedible={value=1,sign="<="}}, prohibit = {"monster"} }, 
    {name = "watermelonicle", name_cn = "西瓜冰棍", health = 3, hunger = 12.5, sanity = 20, type = VEGGIE, perishtime = 1440, cooktime = 0.5, ingredients = {watermelon = {value=1,sign=">="}, frozen = {value=1,sign=">="},twigs = {value=1,sign=">="}}, prohibit = {"inedible","meat","egg"} }, 
    {name = "frognewton", name_cn = "无花果蛙腿三明治", health = 8, hunger = 18.75, sanity = 10, type = MEAT, perishtime = 7200, cooktime = 1, ingredients = {fig = {value=1,sign=">="}, froglegs = {value=1,sign=">="}}, prohibit = {} }, 
    {name = "figkabab", name_cn = "无花果烤串", health = 20, hunger = 25, sanity = 15, type = MEAT, perishtime = 7200, cooktime = 1, ingredients = {meat = {value=1,sign=">="}, twigs = {value=1,sign=">="}, fig={value=1,sign="<="}}, prohibit = {"monster"} }, 
    {name = "sweettea", name_cn = "舒缓茶", health = 3, hunger = 0, sanity = 15, type = , perishtime = 1440, cooktime = 1, ingredients = {forgetmelots = {value=1,sign=">="}, frozen = {value=1,sign=">="}}, prohibit = {"monster","veggie","meat","fish","egg","fat","dairy","inedible"} }, 
    {name = "ceviche", name_cn = "酸橘汁腌鱼", health = 20, hunger = 25, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {fish = {value=2,sign=">="}, frozen = {value=1,sign=">="}}, prohibit = {"inedible","egg"} }, 
    {name = "potatosouffle", name_cn = "蓬松土豆蛋奶酥", health = 20, hunger = 37.5, sanity = 15, type = VEGGIE, perishtime = 4800, cooktime = 2, ingredients = {{potato = {value=2,sign=">="}},{potato = {value=1,sign=">="}, egg = {value=1,sign=">="}}}, prohibit = {"inedible","meat"} }, 
    {name = "pumpkincookie", name_cn = "南瓜饼干", health = 0, hunger = 37.5, sanity = 15, type = VEGGIE, perishtime = 4800, cooktime = 2, ingredients = {pumpkin = {value=1,sign=">="}, sweetener = {value=2,sign=">="}}, prohibit = {} }, 
    {name = "wetgoop", name_cn = "潮湿黏糊", health = 0, hunger = 0, sanity = 0, type = , perishtime = 2880, cooktime = 0.25, ingredients = {}, prohibit = {} }, 
    {name = "barnaclepita", name_cn = "藤壶皮塔饼", health = 20, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 7200, cooktime = 2, ingredients = {barnacle = {value=1,sign=">="}, veggie = {value=0.5,sign=">="}}, prohibit = {} }, 
    {name = "vegstinger", name_cn = "蔬菜鸡尾酒", health = 3, hunger = 25, sanity = 33, type = VEGGIE, perishtime = 7200, cooktime = 0.5, ingredients = {{asparagus = {value=1,sign=">="}, veggie = {value=2,sign=">"}}, {tomato = {value=1,sign=">="}, veggie = {value=2,sign=">"}}}, prohibit = {"inedible","meat","egg"}  }, 
    {name = "unagi", name_cn = "鳗鱼料理", health = 20, hunger = 18.75, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {{cutlichen = {value=1,sign=">="}, eel = {value=1,sign=">"}}, {cutlichen = {value=1,sign=">="}, pondeel = {value=1,sign=">"}},{kelp = {value=1,sign=">="}, eel = {value=1,sign=">"}}, {kelp = {value=1,sign=">="}, pondeel = {value=1,sign=">"}}}, prohibit = {} }, 
    {name = "bonesoup", name_cn = "骨头汤", health = 32, hunger = 150, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 2, ingredients = {boneshard = {value=2,sign="="}, onion = {value=1,sign=">="}, inedible = {value=3,sign="<"}}, prohibit = {} }, 
    {name = "batnosehat", name_cn = "牛奶帽", health = 0, hunger = 3.90625, sanity = 0, type = , perishtime = 7200, cooktime = 2, ingredients = {batnose = {value=1,sign=">="}, kelp = {value=1,sign=">="}, dairy = {value=1,sign=">="}}, prohibit = {} }, 
    {name = "fishtacos", name_cn = "鱼肉玉米卷", health = 20, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 2880, cooktime = 0.5, ingredients = {{fish = {value=0.5,sign=">="}, corn = {value=1,sign=">="}}, {fish = {value=0.5,sign=">="}, oceanfish_small_5_inv = {value=1,sign=">="}}, {fish = {value=0.5,sign=">="}, oceanfish_medium_5_inv = {value=1,sign=">="}}}, prohibit = {} }, 
    {name = "monstertartare", name_cn = "怪物鞑靼", health = -20, hunger = 62.5, sanity = -20, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {monster = {value=2,sign=">="}}, prohibit = {"inedible"} }, 
    {name = "frogfishbowl", name_cn = "蓝带鱼排", health = 20, hunger = 37.5, sanity = -10, type = MEAT, perishtime = 3840, cooktime = 2, ingredients = {froglegs = {value=2,sign=">="}, fish = {value=1,sign=">="}}, prohibit = {"inedible"} }, 
    {name = "dragonchilisalad", name_cn = "辣龙椒沙拉", health = -3, hunger = 25, sanity = 10, type = VEGGIE, perishtime = 7200, cooktime = 0.75, ingredients = {}, prohibit = {} }, 
    {name = "voltgoatjelly", name_cn = "伏特羊肉冻", health = 3, hunger = 37.5, sanity = 10, type = GOODIES, perishtime = 4800, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "barnaclestuffedfishhead", name_cn = "酿鱼头", health = 20, hunger = 75, sanity = 0, type = MEAT, perishtime = 1440, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "frogglebunwich", name_cn = "蛙腿三明治", health = 20, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 7200, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "bunnystew", name_cn = "炖兔子", health = 20, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "bananajuice", name_cn = "香蕉奶昔", health = 8, hunger = 25, sanity = 33, type = VEGGIE, perishtime = 7200, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "glowberrymousse", name_cn = "发光浆果慕斯", health = 3, hunger = 37.5, sanity = 10, type = VEGGIE, perishtime = 3840, cooktime = 1, ingredients = {}, prohibit = {} }, 
    {name = "baconeggs", name_cn = "培根煎蛋", health = 20, hunger = 75, sanity = 5, type = MEAT, perishtime = 9600, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "waffles", name_cn = "华夫饼", health = 60, hunger = 37.5, sanity = 5, type = VEGGIE, perishtime = 2880, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "perogies", name_cn = "波兰水饺", health = 40, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 9600, cooktime = 1, ingredients = {}, prohibit = {} }, 
    {name = "hotchili", name_cn = "辣椒炖肉", health = 20, hunger = 37.5, sanity = 0, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "californiaroll", name_cn = "加州卷", health = 20, hunger = 37.5, sanity = 10, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "bananapop", name_cn = "香蕉冻", health = 20, hunger = 12.5, sanity = 33, type = VEGGIE, perishtime = 1440, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "beefalotreat", name_cn = "皮弗娄牛零食", health = 75, hunger = 25, sanity = 0, type = ROUGHAGE, perishtime = 9600, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "veggieomlet", name_cn = "早餐锅", health = 20, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 9600, cooktime = 1, ingredients = {}, prohibit = {} }, 
    {name = "lobsterbisque", name_cn = "龙虾汤", health = 60, hunger = 25, sanity = 10, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "honeyham", name_cn = "蜜汁火腿", health = 30, hunger = 75, sanity = 5, type = MEAT, perishtime = 7200, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "mashedpotatoes", name_cn = "奶油土豆泥", health = 20, hunger = 37.5, sanity = 33, type = VEGGIE, perishtime = 7200, cooktime = 1, ingredients = {}, prohibit = {} }, 
    {name = "frozenbananadaiquiri", name_cn = "冰香蕉冻唇蜜", health = 30, hunger = 18.75, sanity = 15, type = GOODIES, perishtime = 7200, cooktime = 1, ingredients = {}, prohibit = {} }, 
    {name = "pepperpopper", name_cn = "爆炒填馅辣椒", health = 30, hunger = 25, sanity = -5, type = MEAT, perishtime = 7200, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "seafoodgumbo", name_cn = "海鲜浓汤", health = 40, hunger = 37.5, sanity = 20, type = MEAT, perishtime = 4800, cooktime = 1, ingredients = {}, prohibit = {} }, 
    {name = "potatotornado", name_cn = "花式回旋块茎", health = 3, hunger = 37.5, sanity = 15, type = VEGGIE, perishtime = 4800, cooktime = 0.75, ingredients = {}, prohibit = {} }, 
    {name = "stuffedeggplant", name_cn = "酿茄子", health = 3, hunger = 37.5, sanity = 5, type = VEGGIE, perishtime = 7200, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "guacamole", name_cn = "鳄梨酱", health = 20, hunger = 37.5, sanity = 0, type = MEAT, perishtime = 4800, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "honeynuggets", name_cn = "蜜汁卤肉", health = 20, hunger = 37.5, sanity = 5, type = MEAT, perishtime = 7200, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "trailmix", name_cn = "什锦干果", health = 30, hunger = 12.5, sanity = 5, type = VEGGIE, perishtime = 7200, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "nightmarepie", name_cn = "恐怖国王饼", health = 1, hunger = 25, sanity = 5, type = VEGGIE, perishtime = 4800, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "jammypreserves", name_cn = "果酱", health = 3, hunger = 37.5, sanity = 5, type = VEGGIE, perishtime = 7200, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "barnaclinguine", name_cn = "藤壶中细面", health = 10, hunger = 75, sanity = 20, type = MEAT, perishtime = 2880, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "icecream", name_cn = "冰淇淋", health = 0, hunger = 25, sanity = 50, type = GOODIES, perishtime = 1440, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "beefalofeed", name_cn = "蒸树枝", health = 15, hunger = 100, sanity = 0, type = ROUGHAGE, perishtime = 9600, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "leafymeatburger", name_cn = "素食堡", health = 30, hunger = 37.5, sanity = 33, type = MEAT, perishtime = 2880, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "flowersalad", name_cn = "花沙拉", health = 40, hunger = 12.5, sanity = 5, type = VEGGIE, perishtime = 2880, cooktime = 0.5, ingredients = {}, prohibit = {} }, 
    {name = "koalefig_trunk", name_cn = "无花果酿象鼻", health = 60, hunger = 56.25, sanity = 0, type = MEAT, perishtime = 4800, cooktime = 2, ingredients = {}, prohibit = {} }, 
    {name = "freshfruitcrepes", name_cn = "鲜果可丽饼", health = 60, hunger = 150, sanity = 15, type = VEGGIE, perishtime = 4800, cooktime = 2, ingredients = {}, prohibit = {} }, 
}